<?php

$options = array(
// which string should represent a tab for indentation
    'tabsize' => 4,
);

require_once 'TFSN/Projects.php';
require_once 'TFSN/Get.php';
require_once 'TFSN/CommandLine.php';

$get = new Get();
$params = $get->getParams();

$commandLine = new CommandLine();
$projects = new Projects();


$projectsList = $title = $errors = '';
$projectsList .= $projects->renderProjects();

$siteDirectory = '';
if (array_key_exists('a', $params) && $params['a'] == 'debug' && array_key_exists('site', $params)) {
    $site = $params['site'];
    $siteDirectory = $projects->getDirectoryFromSiteName($site);

    $mageFile = $siteDirectory . 'app/Mage.php';
    if (file_exists($mageFile)) {
        require_once $mageFile;
        Varien_Profiler::enable();
        Mage::setIsDeveloperMode(true);
        umask(0);
        Mage::app((array_key_exists('isAdmin', $params) && $params['isAdmin']) ? 'admin' : '');
        $title = '<img src="' . Mage::getDesign()->getSkinUrl() . Mage::getStoreConfig('design/header/logo_src') . '" /><br />';
        $title .= (array_key_exists('site', $params) ? $params['site'] . ' (<a target="_blank" href="' . Mage::app()->getStore()->getBaseUrl() . '">' . Mage::app()->getStore()->getBaseUrl() . '</a>)' : '');
    }


}
/**
 * PHP Console
 *
 * A web-based php debug console
 *
 * Copyright (C) 2010, Jordi Boggiano
 * http://seld.be/ - j.boggiano@seld.be
 *
 * Licensed under the new BSD License
 * See the LICENSE file for details
 *
 * Source on Github http://github.com/Seldaek/php-console
 */
if (!in_array($_SERVER['REMOTE_ADDR'], array('127.0.0.1', '::1'), true)) {
    if (!file_exists('remote.flag')) {
        header('HTTP/1.1 401 Access unauthorized');
        die('ERR/401 Go Away');
    }
}

define('PHP_CONSOLE_VERSION', '1.3.0-dev');
require 'krumo/class.krumo.php';

ini_set('display_errors', 1);
error_reporting(E_ALL | E_STRICT);

$debugOutput = '';

if (isset($_POST['code'])) {
    $code = $_POST['code'];

    if (get_magic_quotes_gpc()) {
        $code = stripslashes($code);
    }

// if there's only one line wrap it into a krumo() call
    if (preg_match('#^(?!var_dump|echo|print|< )([^\r\n]+?);?\s*$#is', $code, $m) && trim($m[1])) {
        $code = 'krumo(' . $m[1] . ');';
    }

// replace '< foo' by krumo(foo)
    $code = preg_replace('#^<\s+(.+?);?[\r\n]?$#m', 'krumo($1);', $code);

// replace newlines in the entire code block by the new specified one
// i.e. put #\r\n on the first line to emulate a file with windows line
// endings if you're on a unix box
    if (preg_match('{#((?:\\\\[rn]){1,2})}', $code, $m)) {
        $newLineBreak = str_replace(array('\\n', '\\r'), array("\n", "\r"), $m[1]);
        $code = preg_replace('#(\r?\n|\r\n?)#', $newLineBreak, $code);
    }

    ob_start();
    eval($code);
    $debugOutput = ob_get_clean();

    if (isset($_GET['js'])) {
        header('Content-Type: text/plain');
        echo $debugOutput;
        die('#end-php-console-output#');
    }
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Magento/Zend/PHP Debug Console</title>
    <link rel="stylesheet" type="text/css" href="public/assets/styles/styles.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/styles/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/styles/bootstrap-responsive.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/styles/docs.css"/>
    <script src="public/assets/js/jquery-1.7.1.min.js"></script>
    <script src="public/assets/js/jquery-tmpl-min.js"></script>
    <script src="public/assets/js/ace/ace.js"></script>
    <script src="public/assets/js/ace/mode-php.js"></script>
    <script src="public/assets/js/php-console.js"></script>
    <script src="public/assets/js/google-code-prettify/prettify.js"></script>
    <script src="public/assets/js/storage.js"></script>
    <script src="public/assets/js/bootstrap-dropdown.js"></script>
    <link rel="stylesheet" type="text/css" href="public/assets/js/google-code-prettify/prettify.css"/>
    <script>
        $.console({
            tabsize: <?php echo json_encode($options['tabsize']) ?>
        });
    </script>
</head>
<body onload="prettyPrint()">

<?= $this->layout()->content ?>

</body>
</html>
