<?php

$options = array(
// which string should represent a tab for indentation
    'tabsize' => 4,
);


require_once 'TFSN/Get.php';
require_once 'TFSN/CommandLine.php';


/**
 * PHP Console
 *
 * A web-based php debug console
 *
 * Copyright (C) 2010, Jordi Boggiano
 * http://seld.be/ - j.boggiano@seld.be
 *
 * Licensed under the new BSD License
 * See the LICENSE file for details
 *
 * Source on Github http://github.com/Seldaek/php-console
 */

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Magento/Zend/PHP Debug Console</title>
    <link rel="stylesheet" type="text/css" href="/assets/styles/styles.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/styles/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/styles/bootstrap-responsive.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/styles/docs.css"/>
    <script src="/assets/js/jquery-1.7.1.min.js"></script>
    <script src="/assets/js/jquery-tmpl-min.js"></script>
    <script src="/assets/js/ace/ace.js"></script>
    <script src="/assets/js/ace/mode-php.js"></script>
    <script src="/assets/js/php-console.js"></script>
    <script src="/assets/js/google-code-prettify/prettify.js"></script>
    <script src="/assets/js/storage.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <link rel="stylesheet" type="text/css" href="/assets/js/google-code-prettify/prettify.css"/>
    <script>
        $.console({
            tabsize: <?php echo json_encode($options['tabsize']) ?>
        });
    </script>
</head>
<body onload="prettyPrint()">

<?= $this->layout()->content ?>

</body>
</html>
